### ISSUE TITLE
"github.com/brianloveswords/wiretap" dependency disappeared from the internet

### ISSUE THREAD

**Issue by moul** [brianloveswords/airtable#2]
The project cannot build anymore

Do you have an alternative link?

Thank you

**Comment by maqdev** [comment]
@brianloveswords, any chance to recover brianloveswords/wiretap ?

**Comment by moul** [comment]
FYI, I forked this repo and fixed the dep here: https://github.com/moul/brianloveswords-airtable

then, I use "go mod replace" -> https://github.com/moul/depviz/blob/master/go.mod#L5

it's a little bit hacky but allows to continue using brian's code :)

**Comment by maqdev** [comment]
@moul thanks! I couldn't find wiretap anywere

**Comment by moul** [comment]
I just looked at my fix -> https://github.com/moul/brianloveswords-airtable/commit/8b07ee6d33b2dbf8f5c63e90b11e5d2a811575e5

basically, wiretap was a test dependency, I just removed the test completely which removed the project-level dependency on wiretap

**Comment by brianloveswords** [comment]
@moul if you PR that fix I'll accept it.

I unfortunately don't know what happened to `wiretap`—I didn't remove it from GitHub, but it's not in my repositories. It seems like at _some_ point it existed since someone other than me had this working as of Sept 14, 2019, but I can't confirm for sure.

Doubly unfortunate, I don't have the computer I wrote this code on anymore, so I don't have a copy of `wiretap` locally available, so if it's not on GitHub there's a good chance it's gone forever.

**Comment by maqdev** [comment]
Hmm, maybe lets ask Github support what's up with that repo?

**Comment by brianloveswords** [comment]
I submitted a support request to see what's up.

**Comment by moul** [comment]
I just opened the PR to allow this repo to be imported again (without hacks ;p)

-> https://github.com/brianloveswords/airtable/pull/3

**Comment by brianloveswords** [comment]
Thanks again @moul!
